# Elasticsearch values for Camunda Platform Chart.
# https://github.com/camunda/camunda-platform-helm
#
# This configures Elasticsearch when it's used fr Optimize, but NOT as the Camunda secondary storage.
# storage.
#
# For the Elasticsearch as secondary storage configuration, see the
# "camunda-platform-values-elasticsearch.yaml" file.
# If you make changes to this file or the "camunda-platform-values-elasticsearch.yaml" file, make
# sure to keep the other file in sync (minus the secondary storage-only options).

########################################################################################
################################################### Global cluster configuration
########################################################################################
global:
  elasticsearch:
    enabled: true
    url:
      # The Elasticsearch host value used to connect to Elasticsearch depends
      # on the "elasticsearch.fullnameOverride" value.
      # If you change the "elasticsearch.fullnameOverride" value, make sure to
      # update this host value accordingly.
      host: elasticsearch-es-http
